# Generated by Django 5.0.2 on 2026-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Yamaha', 'Yamaha'), ('GPX', 'GPX'), ('RYUKA', 'RYUKA'), ('Lambretta', 'Lambretta'), ('Vespa', 'Vespa')], default='Honda', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
