# Generated by Django 5.0.2 on 2026-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_latitude_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='รหัสไปรษณีย์'),
        ),
    ]
