# Generated by Django 5.0.2 on 2026-02-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-sale_date', '-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ยอดจัด'),
        ),
        migrations.AddField(
            model_name='order',
            name='finance_provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='บริษัทไฟแนนซ์'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ค่างวด'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนงวด'),
        ),
        migrations.AddField(
            model_name='order',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ดอกเบี้ย %'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาขาย'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='api.ordergift'),
        ),
    ]
