# Generated by Django 5.0.2 on 2026-02-06 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_options_order_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPGAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'กำลังชำระ'), ('completed', 'ชำระครบ'), ('closed', 'ปิดบัญชี'), ('overdue', 'เกินกำหนด')], default='active', max_length=20, verbose_name='สถานะ')),
                ('finance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดจัด')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ดอกเบี้ย (%)')),
                ('installment_count', models.IntegerField(verbose_name='จำนวนงวดทั้งหมด')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่างวด')),
                ('period_type', models.CharField(choices=[('รายเดือน', 'รายเดือน'), ('รายปี', 'รายปี')], default='รายเดือน', max_length=20, verbose_name='ประเภท')),
                ('paid_count', models.IntegerField(default=0, verbose_name='งวดที่ชำระแล้ว')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดชำระแล้ว')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='หนี้คงเหลือ')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มจัด')),
                ('next_payment_date', models.DateField(verbose_name='วันชำระถัดไป')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='วันชำระล่าสุด')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='วันปิดบัญชี')),
                ('close_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ยอดปิดบัญชี')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npg_account', to='api.order', verbose_name='ออเดอร์')),
            ],
            options={
                'verbose_name': 'บัญชี NPG',
                'verbose_name_plural': 'บัญชี NPG',
                'db_table': 'npg_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NPGPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ชำระ')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงินที่ชำระ')),
                ('installment_number', models.IntegerField(verbose_name='งวดที่')),
                ('remaining_balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='หนี้คงเหลือหลังชำระ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.npgaccount', verbose_name='บัญชี NPG')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npg_payments', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ประวัติการชำระ NPG',
                'verbose_name_plural': 'ประวัติการชำระ NPG',
                'db_table': 'npg_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
