# Generated by Django 5.0.2 on 2026-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_npgaccount_npgpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='wholesale_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
