# Generated by Django 5.0.2 on 2026-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bike_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='doc_status',
            field=models.CharField(blank=True, choices=[('pending', 'รอเอกสาร'), ('received', 'รับเอกสารแล้ว'), ('fixing', 'แก้เอกสาร'), ('completed', 'ลูกค้ารับเล่มแล้ว')], default='pending', max_length=20, null=True),
        ),
    ]
