# Generated by Django 5.0.2 on 2026-02-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_registrationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('category', models.CharField(choices=[('customer', 'ลูกค้า'), ('inventory', 'สินค้า'), ('system', 'ระบบ'), ('employee', 'พนักงาน'), ('finance', 'การเงิน'), ('other', 'อื่นๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('priority', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'กลาง'), ('high', 'สูง'), ('urgent', 'เร่งด่วน')], default='medium', max_length=10, verbose_name='ระดับความสำคัญ')),
                ('status', models.CharField(choices=[('open', 'เปิด'), ('in_progress', 'กำลังดำเนินการ'), ('resolved', 'แก้ไขแล้ว'), ('closed', 'ปิด')], default='open', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่แก้ไข')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อลูกค้า (ถ้ามี)')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่อ้างอิง (เช่น Order ID)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='มอบหมายให้')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้างกระทู้')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
            ],
            options={
                'verbose_name': 'กระทู้/ปัญหา',
                'verbose_name_plural': 'กระทู้/ปัญหาทั้งหมด',
                'db_table': 'issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ข้อความอัปเดต')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่อัปเดต')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.issue', verbose_name='กระทู้')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้อัปเดต')),
            ],
            options={
                'verbose_name': 'การอัปเดตกระทู้',
                'verbose_name_plural': 'การอัปเดตทั้งหมด',
                'db_table': 'issue_updates',
                'ordering': ['created_at'],
            },
        ),
    ]
