# Generated by Django 5.0.2 on 2026-02-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_issue_issueupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
