# Generated by Django 5.0.2 on 2026-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_check_number_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='api.ordergift'),
        ),
    ]
