# Generated by Django 5.0.2 on 2026-03-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_options_alter_order_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='registration_expiry_date',
            field=models.DateField(blank=True, help_text='วันที่ทะเบียนรถหมดอายุ (สำหรับแจ้งเตือน)', null=True, verbose_name='วันหมดอายุทะเบียน'),
        ),
    ]
