# Generated by Django 5.0.2 on 2026-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_registration_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='registration_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
