# Generated by Django 5.0.2 on 2026-03-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bike_registration_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='chassi',
            new_name='chassis',
        ),
    ]
