# Generated by Django 5.0.2 on 2026-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_chassi_bike_chassis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='chassis',
        ),
        migrations.AddField(
            model_name='bike',
            name='chassi',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Yamaha', 'Yamaha'), ('GPX', 'GPX'), ('RYUKA', 'RYUKA'), ('Lambretta', 'Lambretta'), ('Vespa', 'Vespa')], default='Honda', max_length=20, null=True),
        ),
    ]
